server/products/urls.py
from django.urls import path
from .views import basket_view, basket, add_basket, minus_basket, delete_basket, delete_all_baskets, index

app_name = "products"

urlpatterns = [
    path('basket/', basket_view, name="basket_view"),
    path('add/basket/<int:product_id>/', basket, name="basket"),
    
    # Fnc add and minus qantity basket.
    path('plus/basket/<int:basket_id>/', add_basket, name="add_basket"), 
    path('minus/basket/<int:basket_id>/', minus_basket, name="minus_basket"),
    
    # Delete basket.
    path('delete/basket/<int:basket_id>/', delete_basket, name="delete_basket"),
    path('delete/all/basket/', delete_all_baskets, name="delete_baskets"),

    # Filter urls.
    path('category/<int:category_id>/', index, name="category")
]

server/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

server/users/urls.py
from django.urls import path
from .views import login, sign, user_logout, delete_user

app_name = 'users'

urlpatterns = [
    path('login/', login, name="login"),
    path('sign/', sign, name="sign"),
    path('logout/', user_logout, name="user_logout"),
    path('delete/user/', delete_user, name="delete_user")
]

server/products/models.py
from django.db import models
from users.models import User

class Category(models.Model):
    title = models.CharField(max_length=60)
    
    def __str__(self):
        return f"{self.title}"
    

# Class Product
class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, related_name="products")
    
    def __str__(self):
        return f"{self.title} | {self.price}"
    
# Create class for photo.
class ProductImage(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to="product_image/")

# Manager model Basket.
class Manager(models.QuerySet):
    # total quantity.
    # self == QuerySet
    def total_quantity(self):
        total = 0
        for basket in self:
            total += basket.quantity
        return total
    
    def total_sum(self):
        total = 0
        for basket in self:
            total += basket.sum()
        return total
    
# Basket
class Basket(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()
    date_add = models.DateTimeField(auto_now_add=True)
    objects = Manager.as_manager()
    
    def __str__(self):
        return f"{self.product} for {self.user}"
    
    # Fnc sum for basket.
    def sum(self):
        return self.product.price * self.quantity
    
    # Logic method add and minus qantity basket.
    def add_basket(self):
        if self.quantity <= 6:
            self.quantity += 1
        self.save()
        return self.quantity
    
    def minus_basket(self):
        self.quantity -= 1
        self.save()
        return self.quantity

server/products/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from users.models import User

# Change User.
class ChangeForm(UserChangeForm):
    
    email = forms.EmailField(widget=forms.EmailInput(attrs={ 
        "readonly": True
    }))
    
    image = forms.ImageField(widget=forms.FileInput(attrs={
        "class" : "select_img", "placeholder" : "Выберете изображение"
    }), required=False)
        
    class Meta:
        model = User
        fields = ('username', 'email', 'image')

server/products/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Product, Category, Basket
from django.contrib.auth.decorators import login_required
from .forms import ChangeForm
from django.contrib import messages
from django.shortcuts import get_object_or_404

def index(request, category_id=None):
    products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()
    context = {
        # Правильно решение фильтрации по категориям на сайте.
        "products" : products,
        "categoryies" : Category.objects.all(),
    }
    
    try:
        if Basket.objects.filter(user=request.user).count() >= 1:
            context['basket'] = 1
    except TypeError:
        pass
    
    return render(request, 'products/product.html', context)

@login_required
def basket_view(request):
    if request.method == "POST":
        form = ChangeForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            
            messages.success(request, "Успешно изменили данные")
            return redirect("index")
        else:
            print(form.errors)
    else:
        form = ChangeForm(instance=request.user)
    context = {
        "form" : form,
        'baskets' : Basket.objects.filter(user=request.user)
    }
    return render(request, "products/basket.html", context)

# Logic basket.
@login_required
def basket(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)
    
    if baskets.exists():
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    else:
        Basket.objects.create(user=request.user, product=product, quantity=1)
    
    return redirect(request.META["HTTP_REFERER"])

# Add and minus qantity basket.
@login_required
def add_basket(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.add_basket()
    
    return redirect(request.META["HTTP_REFERER"])

@login_required
def minus_basket(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    count = basket.minus_basket()
    
    if count == 0:
        Basket.objects.get(id=basket_id).delete()
    
    return redirect(request.META["HTTP_REFERER"])

@login_required
def delete_basket(request, basket_id):
    basket = Basket.objects.get(id=basket_id).delete()
    return redirect(request.META['HTTP_REFERER'])

@login_required
def delete_all_baskets(request):
    Basket.objects.filter(user=request.user).delete()
    return redirect(request.META['HTTP_REFERER'])

# Profile change.
# def change_profile(request):
#     if request.method == "POST":
#         form = UserChangeForm(data=request.POST, instance=request.user, files=request.FILES)
#         if form.is_valid():
#             form.save()
            
#             messages.success(request, "Успешно изменили данные")
#             return redirect("index")
#     else:
#         form = UserChangeForm(instance=request.user)
#     context = {
#         "form" : form,
#     }
#     return render(request, 'products/basket.html', context)

server/products/templates/products/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block links %}

    {% endblock links %}
    <title>Oxxxy</title>
</head>
<body class="body">
    <section class="content">
        <header class="header">
            <a href="{% url "index" %}" class="name_logo">OXXXYSHOP</a>
            <nav class="nav">
                <ul>
                    <li><a href="{% url "index" %}" class="head_link">Главная</a></li> 
                    {% if not user.is_authenticated %}
                        <li><a href="sign.html" class="head_link">Создать </a></li>/<li><a href="login.html" class="head_link">Войти</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% block content %}
        
        {% endblock content %}

        {% block footer %}
        
        {% endblock footer %}
    <section>
</body>
</html>
</body>
</html>

server/products/templates/products/basket.html
{% extends "products/base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static "css/profile.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/button.css" %}">
    <link rel="stylesheet" href="{% static "css/basket.css" %}">
{% endblock links %}

{% block content %}
    <section class="center">

        {% comment %} Connection profile section {% endcomment %}
        {% include "products/profile.html" %}

        {% if baskets %}
            <section class="basket">
                <div class="text_basket">
                    <h1>Корзина</h1>
                    <div class="count_product">{{ baskets.total_quantity }}</div>
                </div>

                {% if baskets %}
                    {% for basket in baskets %}
                        <div class="cart_basket">
                            <h1>{{ basket.product.title }}</h1>
                            <p>{{ basket.product.description }}</p>
                            <hr>
                            <div class="cart_count">
                                <div class="number">
                                    <div class="doing">
                                        <a href="{% url "products:add_basket" basket.id %}" class="clean_link">+</a>
                                    </div>
                                    <p>{{ basket.quantity }}</p>
                                    <div class="doing">
                                        <a href="{% url "products:minus_basket" basket.id %}" class="clean_link">-</a>
                                    </div>
                                </div>
                                <p class="price_basket">{{ basket.sum }} руб.</p>
                                <a href="{% url "products:delete_basket" basket.id %}" class="delete_basket_link">Удалить</a>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="total">
                    <p>Итого</p>
                    <p class="price">{{ baskets.total_sum }} руб.</p>
                </div>

                <div class="delete">
                    <a href="{% url "products:delete_baskets" %}" class="delete_basket">Удалить всю корзину</a>
                    <a href="" class="offer_order">Оформить заказ</a>
                </div>
            </section>
        {% else %}
            <h1>Корзина пуста</h1>
        {% endif %}
    </section>
{% endblock content %}

server/products/templates/products/product.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="icon" href="{% static "photo/logo.png" %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/button.css" %}">
    <title>OxxxyShop</title>
</head>
<body class="body">
    <section class="content">
        <header class="header">
            <a href="{% url "index" %}" class="name_logo">OXXXYSHOP</a>
            <nav class="nav">
                <ul>
                    <li><a href="{% url "index" %}" class="head_link">Главная</a></li> 
                    <li><a href="#main" class="head_link">Одежда</a></li>
                    {% if user.is_authenticated and basket >= 1 %}
                        <li><a href="{% url "products:basket_view" %}" class="basket_head_link">Корзина</a></li>
                    {% elif user.is_authenticated %}
                        <li><a href="{% url "products:basket_view" %}" class="head_link">Корзина</a></li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li><a href="{% url "users:sign" %}" class="head_link">Создать </a></li>/<li><a href="{% url "users:login" %}" class="head_link">Войти</a></li>
                    {% else %}
                        <li class="leave_li"><a href="{% url "users:user_logout" %}" class="leave_link head_link">Выход</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        <div class="logo">
            <img src="{% static "photo/Xlogo.gif" %}" alt="">
        </div>
        <hr color="gray">

        <div class="category">
            <nav class="nav_category">
                <ul class="ul_link_category">
                    <li><a href="{% url "index" %}" class="link_category">Все</a></li>
                    {% for category in categoryies %}
                        <li><a href="{% url "products:category" category.id %}" class="link_category">{{ category.title }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
        </div>

        {% if products %}
            <section class="main" id="main">
                {% for product in products %}
                    <div class="product">
                        {% with product.images.first as first_image %}
                            <img src="{{ first_image.image.url }}" alt="Фото продукта" class="photo_product">
                        {% endwith %}
                        <h1 class="name_product">{{ product.title }}</h1>
                        <p class="price_product">{{ product.price }}р.</p>
                        <a class="glow-on-hover primary_button" type="button" href="{% url "products:basket" product.id %}">В корзину</a>
                    </div>
                {% endfor %}
            </section> 
        {% else %}
            <h1>Продуктов в категории нету</h1>
        {% endif %}
    </section>

    <footer class="footer">
        <div class="footer_block">
            <div class="one_footer">
                <div class="first_text_one_footer">
                    <p class="question_order">Вопросы о заказах</p>
                    <div class="links_footer">
                        <a href="" class="button_footer">
                            <i class="bi bi-telegram"></i>
                            Написать
                        </a>
                        <a href="" class="button_footer">
                            <i class="bi bi-instagram"></i>
                            Написать
                        </a>
                    </div>
                    <p class="time_work">Время работы: Пн-Пт с 11:00 до 21:00</p>
                    <p class="email">exapmleemail@gmail.com</p>
                </div>
                <div class="second_text_one_footer">
                    <p class="question_order">Вопросы о заказах</p>
                    <p class="email">examplegmail@gmail.com</p>
                </div>
            </div>

            <div class="two_footer">
                <h1 class="question_order">Магазин</h1>
                <nav class="nav_footer">
                    <ul class="ul_footer">
                        <li><a href="">Магазин</a></li>
                        <li><a href="">Одежда</a></li>
                        <li><a href="">Аксессуары</a></li>
                        <li><a href="">Коллаборации</a></li>
                        <li><a href="">Discount</a></li>
                    </ul>
                </nav>
            </div>

            <div class="two_footer">
                <h1 class="question_order">Информация о магазине</h1>
                <nav class="nav_footer">
                    <ul class="ul_footer">
                        <li><a href="">Поставщик</a></li>
                        <li><a href="">Модели</a></li>
                        <li><a href="">Аксессуары</a></li>
                        <li><a href="">Партнеры</a></li>
                    </ul>
                </nav>
            </div>

            <div class="four_footer">
                <h1 class="name_logo">OXXXMIRON</h1>
                <div class="social">
                    <img src="" alt="">
                    <img src="" alt="">
                    <img src="" alt="">
                    <img src="" alt="">
                </div>
                <div class="information_shop">
                    <p>ИП Федоров Мирон Янович</p>
                    <p>ИНН: 741230764576</p>
                    <p>ОГРНИП: 34560567356299</p>
                </div>
                <p>© 2025 OxxxyShop</p>
            </div>
        </div>
    </footer>
</body>
</html>

server/products/templates/products/profile.html
{% load static %}

<section class="profile">
    <div class="text_profile"><h1>OXXXYSHOP - Профиль({{ user.username }})</h1></div>
    <div class="photo"><img src="{% if user.image %}{{ user.image.url }}{% else %}{% static "photo/profile.png" %}{% endif %}" class="photo_profile" alt="Аватарка пользователя"></div>
    <form action="{% url "products:basket_view" %}" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form_block">
            <div class="username">
                <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="lastname">
                <label for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                {{ form.email }}
            </div>
        </div>
        <label for="{{ form.image.id_for_label }}">Выберете изображение</label>
        {{ form.image }}
        <button class="button_profile">Сохранить</button>        
    </form>
    <a href="{% url "users:delete_user" %}" class="delete_profile">Удалить профиль</a>

    {% if form.errors %}
        <div class="errors" id="error-box">
            <button class="close-btn" onclick="closeErrorBox()">✖</button>
            <h1>Внимание<span>!</span></h1>
            {% for field, error in form.errors.items %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}
        </div>
    {% endif %}

</section>

<script>
    function closeErrorBox() {
        const box = document.getElementById('error-box');
        if (box) {
            box.style.display = 'none';
        }
    }
</script>